export const GET_RESTAURANT_LIST_REQUEST = 'GET_RESTAURANT_LIST_REQUEST';
export const GET_RESTAURANT_LIST_SUCCESS = 'GET_RESTAURANT_LIST_SUCCESS';
export const GET_RESTAURANT_LIST_FAIL = 'GET_RESTAURANT_LIST_FAIL';

export const GET_RESTAURANT_BY_CATEGORY_REQUEST =
  'GET_RESTAURANT_BY_CATEGORY_REQUEST';
export const GET_RESTAURANT_BY_CATEGORY_SUCCESS =
  'GET_RESTAURANT_BY_CATEGORY_SUCCESS';
export const GET_RESTAURANT_BY_CATEGORY_FAIL =
  'GET_RESTAURANT_BY_CATEGORY_FAIL';

export const GET_TOP_RESTAURANT_REQUEST = 'GET_TOP_RESTAURANT_REQUEST';
export const GET_TOP_RESTAURANT_SUCCESS = 'GET_TOP_RESTAURANT_SUCCESS';
export const GET_TOP_RESTAURANT_FAIL = 'GET_TOP_RESTAURANT_FAIL';

export const GET_RESTAURANT_REQUEST = 'GET_RESTAURANT_REQUEST';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS';
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL';

export const GET_RESTAURANT_REVIEWS_REQUEST = 'GET_RESTAURANT_REVIEWS_REQUEST';
export const GET_RESTAURANT_REVIEWS_SUCCESS = 'GET_RESTAURANT_REVIEWS_SUCCESS';
export const GET_RESTAURANT_REVIEWS_FAIL = 'GET_RESTAURANT_REVIEWS_FAIL';

export const CREATE_RESTAURANT_REVIEWS_REQUEST =
  'CREATE_RESTAURANT_REVIEWS_REQUEST';
export const CREATE_RESTAURANT_REVIEWS_SUCCESS =
  'CREATE_RESTAURANT_REVIEWS_SUCCESS';
export const CREATE_RESTAURANT_REVIEWS_FAIL = 'CREATE_RESTAURANT_REVIEWS_FAIL';
export const CREATE_RESTAURANT_REVIEWS_RESET =
  'CREATE_RESTAURANT_REVIEWS_RESET';
